version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - health-checker

  backend:
    image: your-backend-image:latest  # 백엔드 이미지로 변경하세요
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - health-checker

networks:
  health-checker:
    driver: bridge 