spring:
  application:
    name: healthChecker

  ai:
    openai:
      api-key: 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
      base-url: https://api.openai.com/v1/
      chat:
        model: gpt-3.5-turbo
